# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ederm\Desktop\my_projects\repository\qt_designer_files\\track_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(419, 531)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.tracked_file_list = QtWidgets.QListWidget(Dialog)
        self.tracked_file_list.setObjectName("tracked_file_list")
        self.verticalLayout.addWidget(self.tracked_file_list)
        self.add_to_tracked = QtWidgets.QPushButton(Dialog)
        self.add_to_tracked.setObjectName("add_to_tracked")
        self.verticalLayout.addWidget(self.add_to_tracked)
        self.remove_from_tracked = QtWidgets.QPushButton(Dialog)
        self.remove_from_tracked.setObjectName("remove_from_tracked")
        self.verticalLayout.addWidget(self.remove_from_tracked)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.ignore_file_list = QtWidgets.QListWidget(Dialog)
        self.ignore_file_list.setObjectName("ignore_file_list")
        self.verticalLayout.addWidget(self.ignore_file_list)
        self.add_to_ignored = QtWidgets.QPushButton(Dialog)
        self.add_to_ignored.setObjectName("add_to_ignored")
        self.verticalLayout.addWidget(self.add_to_ignored)
        self.remove_from_ignored = QtWidgets.QPushButton(Dialog)
        self.remove_from_ignored.setObjectName("remove_from_ignored")
        self.verticalLayout.addWidget(self.remove_from_ignored)
        self.dialog_buttons = QtWidgets.QDialogButtonBox(Dialog)
        self.dialog_buttons.setOrientation(QtCore.Qt.Horizontal)
        self.dialog_buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.dialog_buttons.setObjectName("dialog_buttons")
        self.verticalLayout.addWidget(self.dialog_buttons)

        self.retranslateUi(Dialog)
        self.dialog_buttons.accepted.connect(Dialog.accept)
        self.dialog_buttons.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Specify files, dirs, file extensions if you want only them to be tracked:"))
        self.add_to_tracked.setText(_translate("Dialog", "Add"))
        self.remove_from_tracked.setText(_translate("Dialog", "Remove"))
        self.label.setText(_translate("Dialog", "File and dir names, file extensions to be ignored:"))
        self.add_to_ignored.setText(_translate("Dialog", "Add"))
        self.remove_from_ignored.setText(_translate("Dialog", "Remove"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
